### ISSUE TITLE
There exists a component named discord.ext.commands by multi#3304

### ISSUE THREAD

**Issue by tripulse** [smetch-discord/smetch-bot#14]
If-elif statements for each possible command is a horrible idea. Shame on you, when you step through to, Discord zoo. Shame on you.

**Comment by telugu-boy** [comment]
I'm the dpy AutoShardedClient.
I never been tooken out, i keep discord.Clients looking out.

Shame on you, when you step through to d.py zoo, d.py zoo, shame on you.

**Comment by tripulse** [comment]
^^^^^^^^^^^3400000001

**Comment by telugu-boy** [comment]
I drop knowledge like STEM dropping moddies,
Enough to make Remceau go crazy

**Comment by telugu-boy** [comment]
In multiple folders using all types of AbstractCogs,
You stemmer thought you were better than,
Oniden engineer, I keep coders in orbit.

**Comment by tripulse** [comment]
nnununununuun

**Comment by telugu-boy** [comment]
Enough `import logging` to make you break ya, shake ya print()
As I create, rhymes good as a paan cupcake makes,
This builtin worth it's faster than print().
Stemmers catching headaches, what what, you need zarda paan!

Shame on you, when you step through to d.py zoo, d.py zoo, shame on you.

**Comment by tripulse** [comment]
^666666666666^

**Comment by telugu-boy** [comment]
It's like an issue, that you could just solve with `pylint`
Mess around and use a tool like `pre-commit`
In your git hooks, format with `black` baby,
Are you listening, at least biswasing now you're learning.
How, I don't even like your stemmer github profile, edit it right right now!

Shame on you, when you step through to d.py zoo, d.py zoo, shame on you.

**Comment by tripulse** [comment]
Shame on you, when you step through to d.py zoo, d.py zoo, shame on you.
My nigga.

**Comment by telugu-boy** [comment]
Shame on you, when you step through to the Ol' Dirty Biswas, d.py zoo, d.py zoo. Shame on you!
Shame on you, when you step through to the Ol' Dirty Biswas, d.py zoo.
Shame on you, my stemmer.

**Comment by nopeless** [comment]
instead of using print just remove them and have unit tests instead

**Comment by telugu-boy** [comment]
this is called a downgrade

**Comment by telugu-boy** [comment]
logging is more beneficial than unit tests

**Comment by nopeless** [comment]
why not log every line then :thinking:

**Comment by telugu-boy** [comment]
log events that happen '-' what

**Comment by tripulse** [comment]
'-'

**Comment by tripulse** [comment]
;0; BIBE v2 "

**Comment by tripulse** [comment]
trilounge.push_back(bibe);
