### ISSUE TITLE
free help channels by Cocánb Altort#3810

### ISSUE THREAD

**Issue by SMETCH-Github** [smetch-discord/smetch-bot#49]
The free help channels are quite spammy sometimes. Even if I already muted a channel before, once it gets occupied and freed again, it gets unmuted automatically (presumably because it creates a new channel with the same name and not by using the original channel) and sends a message which we have to check to clear the unread badge.
Mute a help channel and wait until it gets freed up again
it should continue to be muted

**Comment by doublevcodes** [comment]
I believe this was resolved
